---

authtimeout: 3  #all hosts will have max 3 sec timout
hosts:
- hostname: host1
  ipaddress: 10.233.234.11
  username: student
  password: PanneKake23
  routing-database-hours: 24 #For routingentry collector, data is stored in the database for 24 hours for this host, NB: can not be 0
- hostname: host2
  ipaddress: 10.233.230.11
  username: student
  password: PanneKake23
  routing-database-hours: 24
  exclude:
- hostname: host3
  ipaddress: 10.233.999.11
  username: student
  password: PanneKake23
  routing-database-hours: 24
  exclude:
#  - routingentry
#  - system
#  - diskpartition
#  - systemcallstats
#  - linecard

#Excluding the above collectors for this host
