---

authtimeout: 3  #all hosts will have max 3 sec timout
hosts:
- hostname:
  ipaddress:
  username:
  password:
  routing-database-hours: 24 #For routingentry collector, data is stored in the database for 24 hours for this host
- hostname:
  ipaddress:
  username:
  password:
  routing-database-hours: 24
  exclude:
#  - routingentry
#  - system
#  - diskpartition
#  - systemcallstats
#  - linecard

#Excluding the above collectors for this host