---

authtimeout: 5  #all hosts will have max 5 sec timout
hosts:
- hostname: host1
  ipaddress: 10.233.234.11
  username: student
  password: PanneKake23
- hostname: host2
  ipaddress: 10.233.230.11
  username: student
  password: PanneKake23
  exclude:
    - routingentry
    - system
    - systemcallstats
#Excluding collectors for this host
