package main

import (
	"crypto/tls"
	"fmt"
	"strings"

	//"io/ioutil"
	"net/http"
	"net/url"
)

// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

// curl -k --data "Username=student&Password=PanneKake23" -i -v https://10.233.230.11/rest/login

// TODO: This is insecure; use only in dev environments.
func fetchAPIdata() {

tr := &http.Transport{
	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}
client := &http.Client{Transport: tr}

params := url.Values{}
params.Add("Username", `student`)
params.Add("Password", `PanneKake23`)
body := strings.NewReader(params.Encode())

req, err := http.NewRequest("POST", "https://10.233.230.11/rest/login", body)
if err != nil {
	// handle err
}
req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

resp, err := client.Do(req)
if err != nil {
	// handle err
}
fmt.Println(resp.Body, "HER KOMMER COOKIES", resp.Cookies())
defer resp.Body.Close()
}