---
hosts:
  hostName: host1
  ipaddress: 10.233.234.10
    exclude:
      systemExporter: false
      callStats: true

  hostName: host2
  ipaddress: 10.233.234.10
    exclude:
      systemExporter: false
      callStats: true
